# Generated by Django 5.1.1 on 2024-10-03 09:34

import devices.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packetID', models.CharField(default=0.0)),
                ('timestamp', devices.models.MillisecondDateTimeField(default=django.utils.timezone.now)),
                ('acceleration_x', models.FloatField(default=0.0)),
                ('acceleration_y', models.FloatField(default=0.0)),
                ('acceleration_z', models.FloatField(default=0.0)),
                ('gyro_x', models.FloatField(default=0.0)),
                ('gyro_y', models.FloatField(default=0.0)),
                ('gyro_z', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('battery', models.FloatField(default=100.0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.project'),
        ),
    ]
