# Generated by Django 5.1.1 on 2024-09-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='data',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='acceleration_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='acceleration_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='acceleration_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='battery',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='gyro_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='gyro_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='gyro_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
