# Generated by Django 5.1.1 on 2024-09-23 10:42

import devices.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_device_customer_device_user_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='timestamp',
            field=devices.models.MillisecondDateTimeField(auto_now_add=True),
        ),
    ]
