# Generated by Django 5.1.1 on 2024-09-24 12:13

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_dataentry_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='packetID',
            field=models.CharField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='timestamp',
            field=devices.models.MillisecondDateTimeField(),
        ),
    ]
