# Generated by Django 5.1.1 on 2024-09-25 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.project'),
        ),
    ]
