# Generated by Django 5.1.1 on 2024-09-25 08:31

import devices.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='timestamp',
            field=devices.models.MillisecondDateTimeField(auto_now_add=True),
        ),
    ]
